version: "3"
   
services:

  login-frontend:
    restart: unless-stopped
    build: ./login-frontend
    container_name: login-frontend
    command: python main.py
    volumes:
      - ./login-frontend:/app
    ports:
      - 9898:9898

  login-backend:
    restart: unless-stopped
    build: ./login-backend
    container_name: login-backend
    command: python main.py
    volumes:
      - ./login-backend:/app
    ports:
      - 9899:9899
