version: "3"
   
services:

  login-frontend:
    restart: unless-stopped
    build: .
    container_name: login-frontend
    command: bash run.sh
    volumes:
      - ./login-frontend:/app
    ports:
      - "9898:9898"
    network_mode: host

  login-backend:
    restart: unless-stopped
    build: .
    container_name: login-backend
    command: bash run.sh
    volumes:
      - ./login-backend:/app
    ports:
      - "9899:9899"
    network_mode: host